platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
- name: gcsbeat

run:
  path: ./gcsbeat/ci/scripts/build.sh

params:
  PARAMONE: helloworld
  PROJECT_ID: ((project-id))
