platform: linux

image_resource:
  type: docker-image
  source:
    repository: josephlewis42/gcsbeat-build
    tag: 1.2.0

inputs:
- name: gcsbeat

run:
  path: ./gcsbeat/ci/scripts/build-releases.sh

