platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.10.2

inputs:
- name: gcsbeat

outputs:
- name: releases

run:
  path: ./gcsbeat/ci/scripts/build.sh

