platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
- name: gcsbeat

run:
  path: ./gcsbeat/ci/scripts/build-asdf.sh

params:
  GO_VERSION: 1.10.3
  PYTHON_VERSION: 2.7.15
