platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
- name: gcsbeat

run:
  path: ./gcsbeat/ci/scripts/integration-test.sh

params:
  BUCKET: gcsbeat-integration-test
  SERVICE_ACCOUNT: ((service-account-credentials-json))
