build-interval: 24h

# You will need the following secrets stored in credhub:
# test-gcp-bucket-id - the name of the GCP bucket to run integrations with
# service-account-credentials-json - the full JSON of the service account
# to run tests with, it should have permissions to read, create and delete
# objects in the bucket.
