jobs:
  - name: test
    plan:
    - get: gcsbeat
      trigger: true
    - task: test
      file: gcsbeat/ci/tasks/unit-test.yml
    

resources:
  - name: gcsbeat
    type: git
    source:
      uri: https://github.com/josephlewis42/gcsbeat
      branch: master
