jobs:
  - name: test
    plan:
    - get: gcsbeat
      trigger: true
    - task: test
      file: gcsbeat/ci/tasks/unit-test.yml
  - name: build
    plan:
    - get: gcsbeat
      passed: [test]
      trigger: true
    - task: build
      file: gcsbeat/ci/tasks/build.yml
 - name: build-latest
   plan:
   - get: gcsbeat
     passed: [test]
     trigger: true
   - task: build
     file: gcsbeat/ci/tasks/build-latest.yml
  - name: release
    plan:
    - get: gcsbeat
      passed: [build]
      trigger: true
    - task: release
      file: gcsbeat/ci/tasks/release.yml
    

resources:
  - name: gcsbeat
    type: git
    source:
      uri: https://github.com/josephlewis42/gcsbeat
      branch: master
